spring.application.name=minicore-backend
server.port=${PORT:8080}

# H2 en memoria
spring.datasource.url=jdbc:h2:mem:minicore;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Consola H2 (util para ver la BD en desarrollo)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Cargar seed data despues de crear las tablas
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
